#include "stdafx.h"

// this is now generated by the Diver code tools
extern "C" {
    /*
    __declspec(dllexport) bool WINAPI DllMain(IN HINSTANCE hDllHandle,
        IN DWORD     nReason,
        IN LPVOID    Reserved)
    {
        BOOLEAN bSuccess = TRUE;


        //  Perform global initialization.
        if (DetourIsHelperProcess())
            return bSuccess;


        switch (nReason)
        {
        case DLL_PROCESS_ATTACH:
            DetourRestoreAfterWith();
            OutputDebugString(L"-------------->>>>>>>>>>DebugDotNet Diver Dll Was Loaded<<<<<<<<<<<<<<<<--------");


            break;

        case DLL_PROCESS_DETACH:
            OutputDebugString(L"-------------->>>>>>>>>>DebugDotNet Diver Dll UNloaded<<<<<<<<<<<<<<<<--------");
            break;
        }



        return bSuccess;

    }
    //  end DllMain
    */
}