//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiverTraceApiCodeGen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiverTraceApiCodeGen.MessageStrings", typeof(MessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Requred Temmplate key &apos;{0}&apos; appears missing. This needs to be a non null value and in the template list.
        /// </summary>
        internal static string DetourAttachRequired_KeyMissing {
            get {
                return ResourceManager.GetString("DetourAttachRequired_KeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Template value &apos;{0}&apos; cannot be empty or null.
        /// </summary>
        internal static string DetourAttachRequired_NonNullTemplate {
            get {
                return ResourceManager.GetString("DetourAttachRequired_NonNullTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t export a C/C++ typedef.
        /// </summary>
        internal static string EmitTypeDefBadMsg1 {
            get {
                return ResourceManager.GetString("EmitTypeDefBadMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t import a C/C++ typedef.
        /// </summary>
        internal static string EmitTypeDefBadMsg2 {
            get {
                return ResourceManager.GetString("EmitTypeDefBadMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitting inline prefix unsupported for typedef statement.
        /// </summary>
        internal static string EmitTypeDefBadMsgInline {
            get {
                return ResourceManager.GetString("EmitTypeDefBadMsgInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndentLevel can&apos;t be less than zero.
        /// </summary>
        internal static string IndentLessZeroMessage {
            get {
                return ResourceManager.GetString("IndentLessZeroMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value must be a calling convention only only.
        /// </summary>
        internal static string InvalidCallConvSetMsg {
            get {
                return ResourceManager.GetString("InvalidCallConvSetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required to both be non null and non tempty.
        /// </summary>
        internal static string NonNullAndNonEmptyStringNeeded {
            get {
                return ResourceManager.GetString("NonNullAndNonEmptyStringNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgType or ArgName validation failure..
        /// </summary>
        internal static string ValidateArgFailureMsg {
            get {
                return ResourceManager.GetString("ValidateArgFailureMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation for EmitDeclareFunctionSpecs failed in &quot;{0}.&quot;.
        /// </summary>
        internal static string ValidateCallerFuncFailMsg {
            get {
                return ResourceManager.GetString("ValidateCallerFuncFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}: Function with variable number of arguments must be specified as CDECL in the calling convention.
        /// </summary>
        internal static string ValidateFunctionSpecsEnumCDeclForVargs {
            get {
                return ResourceManager.GetString("ValidateFunctionSpecsEnumCDeclForVargs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Can&apos;t specify both DllExport and DllImport.
        /// </summary>
        internal static string ValidateFunctionSpecsEnumDupDllStuff {
            get {
                return ResourceManager.GetString("ValidateFunctionSpecsEnumDupDllStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed EmitDeclareFunctionSpecs validate.
        /// </summary>
        internal static string ValidateFunctionSpecsEnumFailMsg {
            get {
                return ResourceManager.GetString("ValidateFunctionSpecsEnumFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t specifiy DllExport or DllImport with inline.
        /// </summary>
        internal static string ValidateFunctionSpecsEnumNoInlineDllStuff {
            get {
                return ResourceManager.GetString("ValidateFunctionSpecsEnumNoInlineDllStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Can&apos;t specify multiple Calling Conventions.
        /// </summary>
        internal static string ValidateFunctionSpecsEnumToManyCalling {
            get {
                return ResourceManager.GetString("ValidateFunctionSpecsEnumToManyCalling", resourceCulture);
            }
        }
    }
}
